[platformio]
src_dir = .

[env:cyd2usb]
platform = espressif32@~6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.f_cpu = 160000000L
board_build.partitions = min_spiffs.csv

lib_deps =
    bodmer/TFT_eSPI @ ^2.5.33
    https://github.com/witnessmenow/spotify-api-arduino.git
    bblanchon/ArduinoJson @ ^6.21.3
    https://github.com/tzapu/WiFiManager.git
    bitbank2/JPEGDEC @ ^1.2.8
    ricmoo/QRCode @ ^0.0.1

build_flags =
    -D USER_SETUP_LOADED=1
    -D ILI9341_2_DRIVER=1
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=320
    -D TFT_MISO=12
    -D TFT_MOSI=13
    -D TFT_SCLK=14
    -D TFT_CS=15
    -D TFT_DC=2
    -D TFT_RST=-1
    -D TFT_BL=21
    -D TFT_BACKLIGHT_ON=HIGH
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D LOAD_FONT4=1
    -D LOAD_FONT6=1
    -D LOAD_FONT7=1
    -D LOAD_FONT8=1
    -D LOAD_GFXFF=1
    -D SMOOTH_FONT=1
    -D SPI_FREQUENCY=55000000
    -D SPI_READ_FREQUENCY=20000000
    -D SPI_TOUCH_FREQUENCY=2500000
    -D USE_HSPI_PORT=1
